# Generated by Django 3.2.9 on 2021-11-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='post_date',
            new_name='post',
        ),
    ]
