# Generated by Django 3.2.9 on 2021-11-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_article_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_image',
        ),
    ]
